# Generated by Django 4.0.1 on 2022-01-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
