# Generated by Django 4.0.1 on 2022-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.TextField(blank=True, null=True),
        ),
    ]
