# Generated by Django 4.0.1 on 2022-01-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_category_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.TextField(blank=True, null=True),
        ),
    ]
